#!/bin/sh
device="db2k"
module="db2k"

# force a load
modprobe $module
# turn on logging and debugging
echo 8 > /proc/sys/kernel/printk
echo module db2k +p >/sys/kernel/debug/dynamic_debug/control

mode=666
# remove stale nodes
rm -fr /dev/${device}/*
mkdir /dev/${device} >& /dev/null


# determine which major node we're using
major=`awk '{if ($2 == "db2k") print $1}' /proc/devices`
echo 

mknod /dev/${device}/DaqBoard2K0 c $major 0
mknod /dev/${device}/DaqBoard2K1 c $major 1
mknod /dev/${device}/DaqBoard2K2 c $major 2
mknod /dev/${device}/DaqBoard2K3 c $major 3

# give appropriate group/permissions, and change the group.
# Not all distributions have staff, some have "wheel" instead.
group="staff"
grep -q '^staff:' /etc/group || group="wheel"

chgrp $group /dev/${device}/*
chmod $mode  /dev/${device}/*
